### ISSUE TITLE
Create a test page for different browser behaviors

### ISSUE THREAD

**Issue by robdodson** [WICG/focus-ring#12]
Adding a todo for myself.

It would be useful to have a page with as many focusable elements as we can get on it so we can easily look at the expected focus ring behavior in different browsers. Some users mentioned that removing the focus ring when a user clicks a button on windows would actually change the expected behavior (apparently windows leaves the ring in place for mouse clicks?)

Could maybe repurpose the demo page for this.

**Comment by millette** [comment]
https://wicg.github.io/focus-ring/demo/ was mentionned in #15.

**Comment by robdodson** [comment]
Fixed by #68 which tracks `:focus-ring` behavior. I also have a local copy that tracks `:-moz-focusring` behavior that i may add to this repo or stage separately.
