### ISSUE TITLE
Why capture mode for the keydown event listener?

### ISSUE THREAD

**Issue by kloots** [WICG/focus-ring#19]
Just curious why capture mode is used when binding the `keydown` event listener? (e.g. `document.body.addEventListener('keydown', onKeyDown, true);`). Makes sense for the `focus` and `blur` events as those do not bubble, but `keydown` does.

**Comment by alice** [comment]
I don't remember - I guess so that other listeners don't consume the event?

**Comment by kloots** [comment]
@alice I suppose that make sense. Otherwise if we were relying on bubbling any other keydown listener that called `stopPropagation()` would end up breaking this polyfill.

**Comment by alice** [comment]
@kloots Yep, exactly.
