### ISSUE TITLE
OK to use matches()?

### ISSUE THREAD

**Issue by robdodson** [WICG/focus-ring#2]
I noticed a few lines that use `matches()`
https://github.com/WICG/focus-ring/blob/gh-pages/src/focus-ring.js#L47

But elsewhere the code tries to determine if matches is available:
https://github.com/WICG/focus-ring/blob/gh-pages/src/focus-ring.js#L13

Would it make sense to just use the MDN matches polyfill and patch the `Element.prototype`?
https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Polyfill

**Comment by toolness** [comment]
That seems like a good idea--right now the polyfill raises `Object doesn't support property or method 'matches'` errors on Edge 38.14393.0.0.

Alternatively, you could test for the presence of the API and not load the polyfill if `.matches` doesn't exist?

**Comment by robdodson** [comment]
The matches polyfill linked on MDN is really small so I think even if it's not supported we could recover by adding that in. @alice would you be ok with me doing a PR for this?

**Comment by alice** [comment]
We just need to merge the master branch to gh-pages.

**Comment by robdodson** [comment]
Fixed by #27
