### ISSUE TITLE
How do we handle .focus()?

### ISSUE THREAD

**Issue by robdodson** [WICG/focus-ring#3]
I don't think we currently have a way to handle calling `.focus()` on an element that should self apply `focus-ring`

**Comment by robdodson** [comment]
cc @marcysutton

**Comment by marcysutton** [comment]
The issue I ran into was for programmatic focus with the older CSS Input Modality API–luckily my issue seems to be addressed with your current prototype. The combination of `:focus:not(.focus-ring)` and `:focus-ring` as selectors means focus isn't negated for programmatic input matchers like `body:not([modality=keyboard]) :focus`.

Here's a demo where you can see keyboard & programmatic focus styles working correctly while the mouse focus style is suppressed: http://codepen.io/marcysutton/pen/XMgyPj

**Comment by alice** [comment]
Glad this seems to be working with the updated polyfill!

**Comment by robdodson** [comment]
OK to close this then?

**Comment by marcysutton** [comment]
Seems logical to me, if additional issues come in they could be addressed separately.
