### ISSUE TITLE
Is it possible to style the focus-ring with a box-shadow instead of an outline?

### ISSUE THREAD

**Issue by rchrdnsh** [WICG/focus-ring#40]
That would be fantastic, as that is a very common pattern and one the main reasons why many people disable the outline on focusing-rings. Also want to be able to style it with CSS transitions as well...

...I suppose an example would be every CSS framework ever?... ;-P

**Comment by robdodson** [comment]
Sure you can style `:focus-ring` with whatever you want. 

ex:

```
button:focus-ring {
  box-shadow: 10px 10px 5px #888888;
}
```

**Comment by rchrdnsh** [comment]
noice! this is truly amazing news, indeed! XD Than you, Rob :-)

**Comment by NullVoxPopuli** [comment]
this does not work in firefox :-\
