### ISSUE TITLE
Suggestion: consider offering a distribution without baked-in DOM polyfills

### ISSUE THREAD

**Issue by emilbjorklund** [WICG/focus-ring#44]
One thing currently prohibiting me from using this (very useful) library is that it bakes in polyfills for both `classList` and `matches` (as of v1.0.1) - both of which I already polyfill elsewhere in many of my projects.

Is there any possibility of offering one file in the `dist/` directory that does not include these?

**Comment by emilbjorklund** [comment]
Ah - just saw now that the `classList` lib is not a polyfill per se - which makes it a bit trickier...

**Comment by robdodson** [comment]
I think we removed `matches` in the source.

Does the inclusion of the `classList` polyfill break anything for you, or is this more of a file size concern?

**Comment by emilbjorklund** [comment]
> I think we removed matches in the source.
Yup – I caught that after posting, hence the edit. 😊

> Does the inclusion of the classList polyfill break anything for you, or is this more of a file size concern?

More of a filesize concern, I guess, but also some sort of principle. It's really nice building modern DOM stuff and just polyfilling as needed (and I’m really glad we need less polyfills/libs these days for the simple stuff) but it kinda defeats the purpose if everyone’s polyfilling or including small dependencies to fix minor browser inconsistencies in their own lib, if that makes sense?

Anyway, completely understand if it’s not important at the moment. I notice it’s only used in three places though, so one way of getting rid of the dependency would be to just write it with some old-school `className` manipulation. 😜

**Comment by robdodson** [comment]
It's not that it's not important, I'm just not sure what the best approach is. I guess we could tell folks what we depend on and tell them they need to feature detect and manually load those polyfills themselves? Are there better alternatives that you've seen?

**Comment by robdodson** [comment]
Thinking through this a bit more...

We could tell folks to use polyfill.io to load the necessary polyfills.
Or we could distribute two versions. A polyfilled one and a non-polyfilled one. And let folks decide.

**Comment by emilbjorklund** [comment]
@robdodson Sorry for the radio silence! Re: your previous comment, I personally tend to like the approach of two builds (polyfilled vs non-polyfilled) in general.

**Comment by robdodson** [comment]
Fixed on master.
