### ISSUE TITLE
focus-ring class always being applied on mouse click

### ISSUE THREAD

**Issue by robdodson** [WICG/focus-ring#48]
I noticed a bug related to this chunk of code https://github.com/WICG/focus-ring/blob/master/src/focus-ring.js#L125-L128

[Here's a jsbin to help reproduce](https://output.jsbin.com/fedakoy).

1. Click on the button with a mouse
2. Click in the white space above the button
3. Press Tab to focus the button
4. Click on the white space above the button
5. Click on the button with a mouse, notice the focus-ring class is added.

**Comment by kloots** [comment]
👍
