### ISSUE TITLE
Discrepancy between master and gh-pages branch

### ISSUE THREAD

**Issue by wjdp** [WICG/focus-ring#5]
This repo has two branches, master and gh-pages. I'm assuming gh-pages is the correct one to use as this is the 'default' in the GH interface.

Hit an issue with this setup when sticking the bare repo URL into bower. This clones the master rather than the gh-pages branch.. and the master branch seems to have issues, notably the naming of `isHandlingKeyboardThrottle` / `keyboardThrottleTimeoutID`.  

Error in browser: `Uncaught ReferenceError: isHandlingKeyboardThrottle is not defined
    at HTMLBodyElement.onKeyDown (focus-ring.js:87)`

See https://github.com/WICG/focus-ring/blob/7ff067a8164f4d2db8ebbb0da5c5d3cdb005096d/src/focus-ring.js#L86

**Comment by robdodson** [comment]
I synced up master to gh-pages and rolled out a v1.0.0 tag.
