### ISSUE TITLE
Issues with proper focus styles on selects in Chrome

### ISSUE THREAD

**Issue by esbenam** [WICG/focus-ring#61]
First of all, thank you for all the work you are doing! It is so nice to see work being put into making the creation of accessible user interfaces more accessible!

I have stumbled upon an issue with the demo in Chrome (```Version 61.0.3163.100 (Official Build) (64-bit)``` on OSX).

# The problem
The demo currently leaves the multi-select and the select with a size attribute without any visual focus clues in Chrome. When tabbing to the elements no outline is visible.

The focus works in Firefox and Safari on OSX. Firefox uses the subtle dotted focus around the first item in the select and Safari uses the regular (although slightly thinner) outline around the entire select.

# Potential cause
The current implementation relies on ```outline-width: 0``` instead of ```outline: none```. This seems to have some nice benefits in terms of what needs to be handled by the polyfill (e.g. buttons, selects and radio arrow keys all just work since the ```outline-width: 0``` doesn't affect them for some reason). However for select elements with a multiple or a size attribute the outline is all of a sudden removed (See http://jsbin.com/motuhiwoye/edit?html,css,output).

# Possible solution
One possible solution could be to handle all focusable elements the same by adding .focus-ring explicitly. This way ```outline: none``` could be used instead of ```outline-width: 0```. That would of course make it impossible to recover the initial browser outline styling, but that might be okay since users can always design their own escape hatches. Also that would then add the need for handling more situations (key navigation and more elements) but I can see those scenarios are already being discussed in other issues (https://github.com/WICG/focus-ring/issues/54).

I hope this is helpful. Please let me know if there is anything else I need to do (add examples, create a PR, etc...). Once again thank you for the great work!

**Comment by robdodson** [comment]
Should be fixed by #68. We've updated the guidance to recommend folks us:

```
.js-focus-ring :focus:not(.focus-ring) {
    outline: 0;
}
```

because the behavior of `outline-width` is wonky. The `.js-focus-ring` class helps guard against the javascript failing to load.
