### ISSUE TITLE
Wrong behaviour according to CSS editor drafts?

### ISSUE THREAD

**Issue by AndreasA** [WICG/focus-ring#65]
According to:
https://drafts.csswg.org/selectors-4/#the-focusring-pseudo

The pseudo class focus-ring should always be applied on focus to input elements to indicate a where the user should enter text.
However, it should applied if I select e.g. a link / button element using the keyboard (tab button). 
However, if I do so with the mouse it shouldn't be applied. The reason is that if I tab through links using the keyboard I need to know WHERE I am but I don't need that information if I click on the element.
Of course, it depends on the corresponding browser's heuristics but that part is mentioned as example there.

**Comment by robdodson** [comment]
I'm not sure I understand the issue :)

Are you saying that the polyfill is applying focus-ring when you click on a link or button with a mouse? Can you provide a reproducible test case that demonstrates the problem?

**Comment by AndreasA** [comment]
The polyfill is only applying the style to input fields and only if you use key press like tab in that case.

However, according to documentation it should apply focus-ring always, even in case of mouse click to editable fields. The polyfill doesn't apply focus ring in case of mouse clicks here but it should.
On the other hand, it should instead apply focus-ring to all other elements on focus only when using key press and not mouse clicks. However, the polyfill doesn't apply focus-ring to any other elements at all currently.

See: 
https://github.com/WICG/focus-ring/blob/master/src/focus-ring.js#L97
and
https://github.com/WICG/focus-ring/blob/master/src/focus-ring.js#L30

It therefore only adds the focus-ring class to editable content and only in case of a keypress.

Also check example 34 of the linked documentation
```
For example, UAs typically display focus indicators on text elements whenever they’re focused, to draw attention to the fact that keyboard input will affect their contents.
On the other hand, they typically only display focus indicators on buttons when they were focused by a keyboard interaction (such as tabbing through the document), because it’s not always immediately obvious where the focus will move after such an interaction, but not when they were focused by more "obvious" interactions, like clicking on the button with a mouse pointer.`
```

I could, of course, be wrong with the defintion of focus-ring but not according to the example.

**Comment by robdodson** [comment]
OK thanks I'll look into this. There were some recent changes which seemed to have broken some things. I'm working on a new selenium test runner to better catch these issues.

**Comment by AndreasA** [comment]
OK. I just checked the latest version again and it seems to work correctly now. Maybe I was testing a buggy version before?

**Comment by AndreasA** [comment]
Ah sorry, it was working with 2.0.2 but not with master there it is broken

**Comment by robdodson** [comment]
ok good to know :)

**Comment by AndreasA** [comment]
See also this jsfiddles:
broken: https://jsfiddle.net/yayrqksu/3/ (copied master into script)
working: https://jsfiddle.net/yayrqksu/2/ (copied 2.0.2 dist into script)

One small issue I noticed with v2.0.2 if you tab through both fields and then do another tab to go outside the textfield, in the jsfiddle and then click on the button, the button still receives the focus-ring class but otherwise v2.0.2 seems to work correctly.
