### ISSUE TITLE
white list

### ISSUE THREAD

**Issue by WW3** [WICG/focus-ring#7]
should [contenteditable], video[controls], audio[controls] also be white listed?

**Comment by robdodson** [comment]
I believe items in whitelist are ones that should always display a focus ring.

[contenteditable] seems to, when I try it in Chrome, Firefox, and Safari.

audio and video controls don't seem to in Chrome or Safari but they do in Firefox.

My hunch is we wouldn't want to add those two because they work very similar to `<button>`. @alice wdyt?

**Comment by bradkemper** [comment]
I think the general idea behind showing focus rings on text fields is that you can see where your typing is going to go if you start typing some words. You can then expect to see your words show up within that rectangle. So I would say [contenteditable] should be on the white list, but video controls should not be.

**Comment by jonathantneal** [comment]
Depending on the result of #34, I can file a pull request to whitelist contenteditable.

[Test Page](https://s.codepen.io/jonneal/debug/b8cf0f3cff01f0a628d75f25cf9ac9d0)

I tested that page in **Edge** and **Internet Explorer 11**. None of these elements receive an outline from a pointer, but they all do from keyboard. In Chrome 48, Firefox 53, and Safari 10.1.1, `[contenteditable]` did receive outline from pointer, while media elements did not.

*As an aside, I follow @bradkemper’s rationale, and I think this behavior is unexpected.*

**Comment by kloots** [comment]
@WW3 I've cut a PR to address this issue as the current behavior needs to be tuned IMO. Currently it requires an ARIA role of `textbox` to match and would also match if an element _only_ had a role of `textbox` and no `contenteditable` attribute—which isn't right. I think the right approach is simply keying off of the `contenteditable` attribute.

**Comment by robdodson** [comment]
Looks like this is fixed by https://github.com/WICG/focus-ring/pull/37 so I'm going to close this issue.
