### ISSUE TITLE
Change from 'const' to 'var'

### ISSUE THREAD

**Issue by jeroencornelissen** [WICG/focus-ring#76]
https://github.com/WICG/focus-ring/blob/f70c271888db99b6427ee77571e8fcaff085d196/src/focus-ring.js#L82

Can this `const` not be a `var` like all the other variables?

**Comment by robdodson** [comment]
oops good catch!

**Comment by robdodson** [comment]
Fixed on master. I'll put out a new 3.0.1 release :)
