### ISSUE TITLE
Change name of init function

### ISSUE THREAD

**Issue by jeroencornelissen** [WICG/focus-ring#79]
Isn't it a good idea to rename the `init` function to a less generic name like `initFocusRing`?
I have some other scripts with an `init` function and the focus-ring `init` overrides my init.

https://github.com/WICG/focus-ring/blob/8150e357e75bf9065a919b115ee9bd930d6a96bc/src/focus-ring.js#L4

**Comment by robdodson** [comment]
Are you using `src/focus-ring.js` directly or the version in the `dist` directory? I believe the version in the `dist` directory should be wrapped in a self executing function that scopes everything.

**Comment by jeroencornelissen** [comment]
Thanks, Rob!
